// docs/.vitepress/theme/components/klean/filter-bar/FilterBar.vue
<script setup>
import { computed, nextTick, ref, useAttrs, watch } from 'vue'
import { twMerge } from 'tailwind-merge'
import { filtersEqual } from './filterState.js'

defineOptions({ inheritAttrs: false })

const props = defineProps({
  /** Accessible name for the native search form. */
  label: { type: String, default: 'Filters' },
  /** Prevents duplicate commits while an application visit is pending. */
  busy: { type: Boolean, default: false }
})

const emit = defineEmits(['apply', 'cancel', 'clear', 'remove'])
const value = defineModel({ default: () => ({}) })
const attrs = useAttrs()
const root = ref()
const draft = ref(clone(value.value))

function clone(source) {
  return JSON.parse(JSON.stringify(source ?? {}))
}

const entries = computed(() => Object.entries(value.value ?? {}))
const count = computed(() => entries.value.length)
const dirty = computed(() => !filtersEqual(draft.value, value.value))
const rootAttrs = computed(() => {
  const {
    class: _class,
    onSubmit: _onSubmit,
    onReset: _onReset,
    'data-slot': _dataSlot,
    'data-dirty': _dataDirty,
    'data-empty': _dataEmpty,
    ...rest
  } = attrs
  return rest
})

function setDraft(next) {
  draft.value = clone(
    typeof next === 'function' ? next(clone(draft.value)) : next
  )
}

function update(key, nextValue) {
  setDraft((current) => ({ ...current, [key]: nextValue }))
}

function commit(next, eventName) {
  if (props.busy) return
  const committed = clone(next)
  value.value = committed
  draft.value = clone(committed)
  emit(eventName, clone(committed))
}

function apply() {
  if (!dirty.value) return
  commit(draft.value, 'apply')
}

function cancel() {
  draft.value = clone(value.value)
  emit('cancel', clone(value.value))
}

function clear() {
  if (!count.value) return
  commit({}, 'clear')
}

function focusAfterRemoval(index) {
  nextTick(() => {
    const candidates = [
      ...(root.value?.querySelectorAll?.('[data-filter-remove]') ?? [])
    ]
    const next = candidates[Math.min(index, candidates.length - 1)]
    ;(
      next ??
      root.value?.querySelector?.('[data-filter-clear], [data-filter-trigger]')
    )?.focus?.()
  })
}

function remove(key, event) {
  if (props.busy || !(key in (value.value ?? {}))) return
  const buttons = [
    ...(root.value?.querySelectorAll?.('[data-filter-remove]') ?? [])
  ]
  const index = Math.max(0, buttons.indexOf(event?.currentTarget))
  const next = clone(value.value)
  delete next[key]
  commit(next, 'remove')
  focusAfterRemoval(index)
}

function handleSubmit(event) {
  for (const listener of Array.isArray(attrs.onSubmit)
    ? attrs.onSubmit
    : [attrs.onSubmit]) {
    listener?.(event)
  }
  if (!event.defaultPrevented) {
    event.preventDefault()
    apply()
  }
}

function handleReset(event) {
  for (const listener of Array.isArray(attrs.onReset)
    ? attrs.onReset
    : [attrs.onReset]) {
    listener?.(event)
  }
  if (!event.defaultPrevented) {
    event.preventDefault()
    cancel()
  }
}

function removeAttrs(key, label) {
  return {
    type: 'button',
    disabled: props.busy,
    'aria-label': label ?? `Remove ${key} filter`,
    'data-filter-remove': '',
    'data-filter-key': key,
    onClick: (event) => remove(key, event)
  }
}

const applyAttrs = computed(() => ({
  type: 'submit',
  disabled: props.busy || !dirty.value
}))
const cancelAttrs = computed(() => ({
  type: 'reset',
  disabled: props.busy || !dirty.value
}))
const clearAttrs = computed(() => ({
  type: 'button',
  disabled: props.busy || count.value === 0,
  'data-filter-clear': '',
  onClick: clear
}))

watch(
  value,
  (next) => {
    if (!filtersEqual(next, draft.value)) draft.value = clone(next)
  },
  { deep: true }
)

defineExpose({ root, setDraft, apply, cancel, clear, remove })
</script>

<template>
  <form
    ref="root"
    v-bind="rootAttrs"
    role="search"
    :aria-label="label"
    :aria-busy="busy ? 'true' : undefined"
    data-slot="filter-bar"
    :data-dirty="dirty ? '' : undefined"
    :data-empty="count === 0 ? '' : undefined"
    :class="twMerge('flex flex-wrap items-center gap-2', attrs.class)"
    @submit="handleSubmit"
    @reset="handleReset"
  >
    <slot
      :draft="draft"
      :entries="entries"
      :count="count"
      :dirty="dirty"
      :busy="busy"
      :set-draft="setDraft"
      :update="update"
      :apply="apply"
      :cancel="cancel"
      :clear="clear"
      :remove="remove"
      :remove-attrs="removeAttrs"
      :apply-attrs="applyAttrs"
      :cancel-attrs="cancelAttrs"
      :clear-attrs="clearAttrs"
    />
    <span class="sr-only" aria-live="polite" aria-atomic="true">
      {{ count }} active {{ count === 1 ? 'filter' : 'filters' }}.
    </span>
  </form>
</template>

// docs/klean-ui/sources/filter-bar/FilterBar.svelte
<script>
  import { untrack } from "svelte";
  import { twMerge } from "tailwind-merge";
  import { filtersEqual, stableFilters } from "./filterState.js";

  let {
    value = $bindable(),
    defaultValue = {},
    label = "Filters",
    busy = false,
    class: className = "",
    children,
    onchange,
    onapply,
    oncancel,
    onclear,
    onremove,
    onsubmit,
    onreset,
    "data-slot": _dataSlot,
    "data-dirty": _dataDirty,
    "data-empty": _dataEmpty,
    ...formProps
  } = $props();

  function clone(source) {
    return JSON.parse(JSON.stringify(source ?? {}));
  }

  let formElement;
  let internalValue = $state(clone(untrack(() => defaultValue)));
  let committed = $derived(value !== undefined ? value : internalValue);
  let committedSignature = $derived(stableFilters(committed));
  let draft = $state(clone(untrack(() => committed)));
  let entries = $derived(Object.entries(committed ?? {}));
  let count = $derived(entries.length);
  let dirty = $derived(!filtersEqual(draft, committed));
  let previousSignature = untrack(() => committedSignature);

  $effect(() => {
    const signature = committedSignature;
    if (signature !== previousSignature) {
      draft = clone(committed);
      previousSignature = signature;
    }
  });

  function setDraft(next) {
    draft = clone(typeof next === "function" ? next(clone(draft)) : next);
  }

  function update(key, nextValue) {
    draft = { ...draft, [key]: nextValue };
  }

  function commit(next, callback) {
    if (busy) return;
    const committedNext = clone(next);
    if (value === undefined) internalValue = committedNext;
    else value = committedNext;
    draft = clone(committedNext);
    onchange?.(clone(committedNext));
    callback?.(clone(committedNext));
  }

  function apply() {
    if (!dirty) return;
    commit(draft, onapply);
  }

  function cancel() {
    const next = clone(committed);
    draft = next;
    oncancel?.(clone(next));
  }

  function clear() {
    if (!count) return;
    commit({}, onclear);
  }

  function focusAfterRemoval(index) {
    setTimeout(() => {
      const buttons = [
        ...(formElement?.querySelectorAll?.("[data-filter-remove]") ?? []),
      ];
      const next = buttons[Math.min(index, buttons.length - 1)];
      (
        next ??
        formElement?.querySelector?.(
          "[data-filter-clear], [data-filter-trigger]",
        )
      )?.focus?.();
    });
  }

  function remove(key, event) {
    if (busy || !(key in (committed ?? {}))) return;
    const buttons = [
      ...(formElement?.querySelectorAll?.("[data-filter-remove]") ?? []),
    ];
    const index = Math.max(0, buttons.indexOf(event?.currentTarget));
    const next = clone(committed);
    delete next[key];
    commit(next, (filters) => onremove?.(filters, key));
    focusAfterRemoval(index);
  }

  function handleSubmit(event) {
    onsubmit?.(event);
    if (!event.defaultPrevented) {
      event.preventDefault();
      apply();
    }
  }

  function handleReset(event) {
    onreset?.(event);
    if (!event.defaultPrevented) {
      event.preventDefault();
      cancel();
    }
  }

  function removeProps(key, removeLabel) {
    return {
      type: "button",
      disabled: busy,
      "aria-label": removeLabel ?? `Remove ${key} filter`,
      "data-filter-remove": "",
      "data-filter-key": key,
      onclick: (event) => remove(key, event),
    };
  }

  let state = $derived({
    draft,
    setDraft,
    entries,
    count,
    dirty,
    busy,
    update,
    apply,
    cancel,
    clear,
    remove,
    removeProps,
    applyProps: { type: "submit", disabled: busy || !dirty },
    cancelProps: { type: "reset", disabled: busy || !dirty },
    clearProps: {
      type: "button",
      disabled: busy || count === 0,
      "data-filter-clear": "",
      onclick: clear,
    },
  });
</script>

<form
  {...formProps}
  bind:this={formElement}
  role="search"
  aria-label={label}
  aria-busy={busy ? "true" : undefined}
  data-slot="filter-bar"
  data-dirty={dirty ? "" : undefined}
  data-empty={count === 0 ? "" : undefined}
  class={twMerge("flex flex-wrap items-center gap-2", className)}
  onsubmit={handleSubmit}
  onreset={handleReset}
>
  {@render children?.(state)}
  <span class="sr-only" aria-live="polite" aria-atomic="true">
    {count} active {count === 1 ? "filter" : "filters"}.
  </span>
</form>
