// docs/.vitepress/theme/components/klean/table/Table.vue
<script setup>
import { computed, ref, useAttrs } from 'vue'
import { twMerge } from 'tailwind-merge'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()
const element = ref()

const forwardedAttrs = computed(() => {
  const { class: _class, 'data-slot': _dataSlot, ...rest } = attrs
  return rest
})

defineExpose({ element })
</script>

<template>
  <table
    ref="element"
    v-bind="forwardedAttrs"
    data-slot="table"
    :class="
      twMerge(
        'w-full border-collapse text-left text-sm text-gray-950 dark:text-white',
        attrs.class
      )
    "
  >
    <slot />
  </table>
</template>

// docs/klean-ui/sources/table/Table.svelte
<script>
  import { twMerge } from "tailwind-merge";

  let {
    children,
    class: className,
    "data-slot": _dataSlot,
    ...props
  } = $props();

  let element;

  export function getElement() {
    return element;
  }
</script>

<table
  {...props}
  bind:this={element}
  data-slot="table"
  class={twMerge(
    "w-full border-collapse text-left text-sm text-gray-950 dark:text-white",
    className,
  )}
>
  {@render children?.()}
</table>
