// docs/klean-ui/sources/radio/Radio.jsx
import { forwardRef, useCallback, useEffect, useRef, useState } from 'react'
import { twMerge } from 'tailwind-merge'

const BASE_CLASSES = [
  'size-4 shrink-0 cursor-pointer appearance-auto accent-current text-gray-950 outline-none',
  'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-950',
  'disabled:cursor-not-allowed disabled:opacity-50',
  'aria-invalid:focus-visible:outline-red-600',
  'dark:text-white dark:focus-visible:outline-white dark:aria-invalid:focus-visible:outline-red-500'
]

function assignRef(ref, value) {
  if (typeof ref === 'function') ref(value)
  else if (ref) ref.current = value
}

const Radio = forwardRef(function Radio(
  {
    checked,
    defaultChecked = false,
    disabled = false,
    value = 'on',
    'aria-invalid': ariaInvalid,
    className,
    onChange,
    'data-slot': _dataSlot,
    'data-state': _dataState,
    'data-disabled': _dataDisabled,
    'data-invalid': _dataInvalid,
    ...props
  },
  forwardedRef
) {
  const elementRef = useRef(null)
  const controlled = checked !== undefined
  const [localChecked, setLocalChecked] = useState(Boolean(defaultChecked))
  const resolvedChecked = controlled ? Boolean(checked) : localChecked
  const invalid = ariaInvalid === true || ariaInvalid === 'true'

  const setElement = useCallback(
    (node) => {
      elementRef.current = node
      assignRef(forwardedRef, node)
    },
    [forwardedRef]
  )

  useEffect(() => {
    const node = elementRef.current
    if (!node || controlled) return

    const root = node.form ?? node.getRootNode()

    function syncGroupState(event) {
      const target = event.target
      if (
        target?.type !== 'radio' ||
        target.name !== node.name ||
        target.form !== node.form
      ) {
        return
      }

      setLocalChecked(node.checked)
    }

    function handleReset() {
      queueMicrotask(() => setLocalChecked(node.checked))
    }

    root?.addEventListener('change', syncGroupState)
    node.form?.addEventListener('reset', handleReset)

    return () => {
      root?.removeEventListener('change', syncGroupState)
      node.form?.removeEventListener('reset', handleReset)
    }
  }, [controlled])

  function handleChange(event) {
    if (!controlled) setLocalChecked(event.target.checked)
    onChange?.(event)
  }

  return (
    <input
      {...props}
      ref={setElement}
      type="radio"
      checked={controlled ? Boolean(checked) : undefined}
      defaultChecked={controlled ? undefined : Boolean(defaultChecked)}
      disabled={disabled}
      value={value}
      aria-invalid={ariaInvalid}
      data-slot="radio"
      data-state={resolvedChecked ? 'checked' : 'unchecked'}
      data-disabled={disabled ? '' : undefined}
      data-invalid={invalid ? '' : undefined}
      className={twMerge(BASE_CLASSES, className)}
      onChange={handleChange}
    />
  )
})

export default Radio

// docs/klean-ui/sources/radio/Radio.svelte
<script>
  import { twMerge } from "tailwind-merge";

  const BASE_CLASSES = [
    "size-4 shrink-0 cursor-pointer appearance-auto accent-current text-gray-950 outline-none",
    "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-950",
    "disabled:cursor-not-allowed disabled:opacity-50",
    "aria-invalid:focus-visible:outline-red-600",
    "dark:text-white dark:focus-visible:outline-white dark:aria-invalid:focus-visible:outline-red-500",
  ];

  let {
    group = $bindable(),
    value = "on",
    disabled = false,
    class: className,
    type: _type,
    checked: _checked,
    "data-slot": _dataSlot,
    "data-state": _dataState,
    "data-disabled": _dataDisabled,
    "data-invalid": _dataInvalid,
    ...props
  } = $props();

  let element = $state();
  let initialChecked;
  let state = $derived(Object.is(group, value) ? "checked" : "unchecked");
  let invalid = $derived(
    props["aria-invalid"] === true || props["aria-invalid"] === "true",
  );

  function groupHasCheckedRadio(node) {
    const root = node.form ?? node.getRootNode();
    const controls =
      node.form?.elements ??
      root?.querySelectorAll?.('input[type="radio"]') ??
      [];

    return Array.from(controls).some(
      (control) =>
        control.type === "radio" &&
        control.name === node.name &&
        control.form === node.form &&
        control.checked,
    );
  }

  $effect(() => {
    const node = element;
    if (!node) return;

    if (initialChecked === undefined) {
      initialChecked = Object.is(group, value);
      node.defaultChecked = initialChecked;
    }

    function handleReset() {
      queueMicrotask(() => {
        if (node.checked) group = value;
        else if (!groupHasCheckedRadio(node)) group = undefined;
      });
    }

    node.form?.addEventListener("reset", handleReset);
    return () => node.form?.removeEventListener("reset", handleReset);
  });

  export function getElement() {
    return element;
  }

  export function focus(options) {
    element?.focus(options);
  }
</script>

<input
  {...props}
  bind:this={element}
  bind:group
  type="radio"
  {value}
  {disabled}
  data-slot="radio"
  data-state={state}
  data-disabled={disabled ? "" : undefined}
  data-invalid={invalid ? "" : undefined}
  class={twMerge(BASE_CLASSES, className)}
/>
