// docs/klean-ui/sources/menu/Menu.jsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState
} from 'react'
import { twMerge } from 'tailwind-merge'
import Popover from '../popover/Popover.jsx'

const ITEM_SELECTOR =
  '[role="menuitem"], [role="menuitemcheckbox"], [role="menuitemradio"]'

function eventPath(event) {
  return (
    event.nativeEvent?.composedPath?.() ??
    event.composedPath?.() ?? [event.target]
  )
}

function itemRole(element) {
  return ['menuitem', 'menuitemcheckbox', 'menuitemradio'].includes(
    element.getAttribute('role')
  )
}

function itemIsDisabled(item) {
  return (
    item.matches(':disabled') ||
    item.getAttribute('aria-disabled') === 'true' ||
    item.hidden ||
    item.closest('[hidden]') !== null
  )
}

const Menu = forwardRef(function Menu(
  {
    id,
    open: controlledOpen,
    defaultOpen = false,
    onOpenChange,
    placement = 'bottom-start',
    offset = 8,
    className,
    children,
    onKeyDown,
    onClickCapture,
    ...contentProps
  },
  forwardedRef
) {
  const popoverRef = useRef(null)
  const activeInvoker = useRef(null)
  const pendingFocus = useRef('first')
  const restoreOnClose = useRef(false)
  const typeahead = useRef('')
  const typeaheadTimer = useRef()
  const [internalOpen, setInternalOpen] = useState(defaultOpen)
  const isControlled = controlledOpen !== undefined
  const isOpen = isControlled ? controlledOpen : internalOpen
  const latestOpen = useRef(isOpen)
  latestOpen.current = isOpen

  const contentElement = useCallback(() => popoverRef.current?.content, [])

  const invokers = useCallback(() => {
    const content = contentElement()
    const root = content?.getRootNode?.() ?? document

    return [...(root.querySelectorAll?.('[popovertarget]') ?? [])].filter(
      (element) => element.getAttribute('popovertarget') === content?.id
    )
  }, [contentElement])

  const syncInvokerSemantics = useCallback(() => {
    for (const invoker of invokers()) {
      invoker.setAttribute('aria-haspopup', 'menu')
    }
  }, [invokers])

  const matchingInvoker = useCallback(
    (event) => {
      const contentId = contentElement()?.id
      return eventPath(event).find(
        (element) => element?.getAttribute?.('popovertarget') === contentId
      )
    },
    [contentElement]
  )

  const restoreInvokerFocus = useCallback(() => {
    const invoker = activeInvoker.current?.isConnected
      ? activeInvoker.current
      : invokers()[0]
    invoker?.focus?.({ preventScroll: true })
  }, [invokers])

  const menuItems = useCallback(() => {
    const content = contentElement()
    if (!content) return []

    for (const element of content.querySelectorAll('button, a[href]')) {
      if (!element.hasAttribute('role'))
        element.setAttribute('role', 'menuitem')
    }

    const items = [...content.querySelectorAll(ITEM_SELECTOR)].filter(
      (element) => element.closest('[role="menu"]') === content
    )
    for (const item of items) item.tabIndex = -1
    return items
  }, [contentElement])

  const enabledItems = useCallback(
    () => menuItems().filter((item) => !itemIsDisabled(item)),
    [menuItems]
  )

  const focusedElement = useCallback(
    () =>
      contentElement()?.getRootNode?.().activeElement ?? document.activeElement,
    [contentElement]
  )

  const focusItem = useCallback(
    (item) => {
      if (!item) return
      for (const candidate of menuItems()) candidate.tabIndex = -1
      item.tabIndex = 0
      item.focus({ preventScroll: true })
    },
    [menuItems]
  )

  const focusEdge = useCallback(
    (edge = 'first') => {
      const items = enabledItems()
      const item = edge === 'last' ? items.at(-1) : items[0]
      if (item) focusItem(item)
      else contentElement()?.focus({ preventScroll: true })
    },
    [contentElement, enabledItems, focusItem]
  )

  const clearTypeahead = useCallback(() => {
    typeahead.current = ''
    clearTimeout(typeaheadTimer.current)
    typeaheadTimer.current = undefined
  }, [])

  const requestOpen = useCallback(
    (nextOpen) => {
      if (!isControlled) setInternalOpen(nextOpen)
      onOpenChange?.(nextOpen)
    },
    [isControlled, onOpenChange]
  )

  const openMenu = useCallback(
    (edge = 'first') => {
      pendingFocus.current = edge
      if (latestOpen.current) focusEdge(edge)
      else requestOpen(true)
    },
    [focusEdge, requestOpen]
  )

  const closeMenu = useCallback(
    ({ restoreFocus = false } = {}) => {
      restoreOnClose.current ||= restoreFocus
      if (latestOpen.current) requestOpen(false)
      else if (restoreOnClose.current) {
        restoreOnClose.current = false
        queueMicrotask(restoreInvokerFocus)
      }
    },
    [requestOpen, restoreInvokerFocus]
  )

  useImperativeHandle(
    forwardedRef,
    () => ({ content: contentElement(), open: openMenu, close: closeMenu }),
    [closeMenu, contentElement, openMenu]
  )

  useEffect(() => {
    syncInvokerSemantics()

    if (isOpen) {
      focusEdge(pendingFocus.current)
      pendingFocus.current = 'first'
      return
    }

    clearTypeahead()
    menuItems()
    if (restoreOnClose.current) restoreInvokerFocus()
    restoreOnClose.current = false
  }, [
    clearTypeahead,
    focusEdge,
    isOpen,
    menuItems,
    restoreInvokerFocus,
    syncInvokerSemantics
  ])

  useEffect(() => {
    const content = contentElement()
    const root = content?.getRootNode?.() ?? document

    function rememberInvoker(event) {
      const invoker = matchingInvoker(event)
      if (invoker) activeInvoker.current = invoker
    }

    function handleInvokerKeydown(event) {
      const invoker = matchingInvoker(event)
      if (!invoker || invoker.matches(':disabled')) return
      activeInvoker.current = invoker

      if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
        event.preventDefault()
        openMenu(event.key === 'ArrowUp' ? 'last' : 'first')
      }
    }

    root.addEventListener('keydown', handleInvokerKeydown)
    root.addEventListener('click', rememberInvoker, true)
    syncInvokerSemantics()
    menuItems()

    const observer =
      typeof MutationObserver !== 'undefined' && content
        ? new MutationObserver(menuItems)
        : undefined
    observer?.observe(content, { childList: true, subtree: true })

    return () => {
      observer?.disconnect()
      root.removeEventListener('keydown', handleInvokerKeydown)
      root.removeEventListener('click', rememberInvoker, true)
      clearTypeahead()
    }
  }, [
    clearTypeahead,
    contentElement,
    matchingInvoker,
    menuItems,
    openMenu,
    syncInvokerSemantics
  ])

  function itemFromEvent(event) {
    const content = contentElement()
    return eventPath(event).find(
      (element) =>
        element?.nodeType === 1 &&
        itemRole(element) &&
        element.closest?.('[role="menu"]') === content
    )
  }

  function handleClick(event) {
    const item = itemFromEvent(event)
    if (!item) {
      onClickCapture?.(event)
      return
    }

    if (itemIsDisabled(item)) {
      event.preventDefault()
      event.nativeEvent.stopImmediatePropagation()
      return
    }

    closeMenu({ restoreFocus: true })
    onClickCapture?.(event)
  }

  function handleTypeahead(event) {
    if (
      event.key.length !== 1 ||
      event.key === ' ' ||
      event.altKey ||
      event.ctrlKey ||
      event.metaKey
    ) {
      return false
    }

    event.preventDefault()
    clearTimeout(typeaheadTimer.current)
    typeahead.current += event.key.toLocaleLowerCase()
    typeaheadTimer.current = setTimeout(clearTypeahead, 500)

    const items = enabledItems()
    if (!items.length) return true
    const current = items.indexOf(focusedElement())
    const ordered = [
      ...items.slice(current + 1),
      ...items.slice(0, current + 1)
    ]
    const itemText = (item) =>
      (item.getAttribute('aria-label') ?? item.textContent ?? '')
        .trim()
        .toLocaleLowerCase()
    let match = ordered.find((item) =>
      itemText(item).startsWith(typeahead.current)
    )

    if (!match && new Set(typeahead.current).size === 1) {
      typeahead.current = typeahead.current.at(-1)
      match = ordered.find((item) =>
        itemText(item).startsWith(typeahead.current)
      )
    }

    if (match) focusItem(match)
    return true
  }

  function handleKeydown(event) {
    const items = enabledItems()
    const currentIndex = items.indexOf(focusedElement())
    let nextIndex

    if (event.key === 'Escape') {
      event.preventDefault()
      event.stopPropagation()
      closeMenu({ restoreFocus: true })
    } else if (event.key === 'Tab') {
      clearTypeahead()
      closeMenu()
    } else if (event.key === 'ArrowDown') {
      nextIndex = currentIndex < 0 ? 0 : (currentIndex + 1) % items.length
    } else if (event.key === 'ArrowUp') {
      nextIndex =
        currentIndex < 0
          ? items.length - 1
          : (currentIndex - 1 + items.length) % items.length
    } else if (event.key === 'Home') {
      nextIndex = 0
    } else if (event.key === 'End') {
      nextIndex = items.length - 1
    } else if (!handleTypeahead(event)) {
      onKeyDown?.(event)
      return
    }

    if (nextIndex !== undefined && items.length) {
      event.preventDefault()
      focusItem(items[nextIndex])
    }
    onKeyDown?.(event)
  }

  return (
    <Popover
      {...contentProps}
      ref={popoverRef}
      id={id}
      open={isOpen}
      onOpenChange={requestOpen}
      placement={placement}
      offset={offset}
      role="menu"
      tabIndex={-1}
      data-slot="menu"
      className={twMerge('min-w-40 p-1', className)}
      onClickCapture={handleClick}
      onKeyDown={handleKeydown}
    >
      {typeof children === 'function'
        ? children({ open: isOpen, close: closeMenu })
        : children}
    </Popover>
  )
})

export default Menu

// docs/klean-ui/sources/menu/Menu.svelte
<script>
  import { onMount, untrack } from "svelte";
  import { twMerge } from "tailwind-merge";
  import Popover from "../popover/Popover.svelte";

  let {
    id,
    open = $bindable(),
    defaultOpen = false,
    onOpenChange,
    placement = "bottom-start",
    offset = 8,
    class: className = "",
    children,
    onkeydown,
    onclickcapture,
    ...contentProps
  } = $props();

  let popoverElement = $state();
  let internalOpen = $state(untrack(() => defaultOpen));
  let activeInvoker = $state();
  let isOpen = $derived(open ?? internalOpen);
  let pendingFocus = "first";
  let restoreOnClose = false;
  let typeahead = "";
  let typeaheadTimer;

  function contentElement() {
    return popoverElement?.getContent?.();
  }

  function eventPath(event) {
    return event.composedPath?.() ?? [event.target];
  }

  function invokers() {
    const content = contentElement();
    const root = content?.getRootNode?.() ?? document;

    return [...(root.querySelectorAll?.("[popovertarget]") ?? [])].filter(
      (element) => element.getAttribute("popovertarget") === content?.id,
    );
  }

  function syncInvokerSemantics() {
    for (const invoker of invokers()) {
      invoker.setAttribute("aria-haspopup", "menu");
    }
  }

  function matchingInvoker(event) {
    const contentId = contentElement()?.id;
    return eventPath(event).find(
      (element) => element?.getAttribute?.("popovertarget") === contentId,
    );
  }

  function restoreInvokerFocus() {
    const invoker = activeInvoker?.isConnected ? activeInvoker : invokers()[0];
    invoker?.focus?.({ preventScroll: true });
  }

  function itemRole(element) {
    return ["menuitem", "menuitemcheckbox", "menuitemradio"].includes(
      element.getAttribute("role"),
    );
  }

  function menuItems() {
    const content = contentElement();
    if (!content) return [];

    for (const element of content.querySelectorAll("button, a[href]")) {
      if (!element.hasAttribute("role")) element.setAttribute("role", "menuitem");
    }

    const items = [
      ...content.querySelectorAll(
        '[role="menuitem"], [role="menuitemcheckbox"], [role="menuitemradio"]',
      ),
    ].filter((element) => element.closest('[role="menu"]') === content);

    for (const item of items) item.tabIndex = -1;
    return items;
  }

  function itemIsDisabled(item) {
    return (
      item.matches(":disabled") ||
      item.getAttribute("aria-disabled") === "true" ||
      item.hidden ||
      item.closest("[hidden]") !== null
    );
  }

  function enabledItems() {
    return menuItems().filter((item) => !itemIsDisabled(item));
  }

  function focusedElement() {
    return contentElement()?.getRootNode?.().activeElement ?? document.activeElement;
  }

  function focusItem(item) {
    if (!item) return;
    for (const candidate of menuItems()) candidate.tabIndex = -1;
    item.tabIndex = 0;
    item.focus({ preventScroll: true });
  }

  function focusEdge(edge = "first") {
    const items = enabledItems();
    const item = edge === "last" ? items.at(-1) : items[0];
    if (item) focusItem(item);
    else contentElement()?.focus({ preventScroll: true });
  }

  function clearTypeahead() {
    typeahead = "";
    clearTimeout(typeaheadTimer);
    typeaheadTimer = undefined;
  }

  function normalizedText(item) {
    return (item.getAttribute("aria-label") ?? item.textContent ?? "")
      .trim()
      .toLocaleLowerCase();
  }

  function handleTypeahead(event) {
    if (
      event.key.length !== 1 ||
      event.key === " " ||
      event.altKey ||
      event.ctrlKey ||
      event.metaKey
    ) {
      return false;
    }

    event.preventDefault();
    clearTimeout(typeaheadTimer);
    typeahead += event.key.toLocaleLowerCase();
    typeaheadTimer = setTimeout(clearTypeahead, 500);

    const items = enabledItems();
    if (!items.length) return true;
    const current = items.indexOf(focusedElement());
    const ordered = [...items.slice(current + 1), ...items.slice(0, current + 1)];
    let match = ordered.find((item) => normalizedText(item).startsWith(typeahead));

    if (!match && new Set(typeahead).size === 1) {
      typeahead = typeahead.at(-1);
      match = ordered.find((item) => normalizedText(item).startsWith(typeahead));
    }

    if (match) focusItem(match);
    return true;
  }

  function requestOpen(nextOpen) {
    if (open === undefined) internalOpen = nextOpen;
    else open = nextOpen;
    onOpenChange?.(nextOpen);
  }

  function openMenu(edge = "first") {
    pendingFocus = edge;
    if (isOpen) focusEdge(edge);
    else requestOpen(true);
  }

  function closeMenu({ restoreFocus = false } = {}) {
    restoreOnClose ||= restoreFocus;
    if (isOpen) requestOpen(false);
    else if (restoreOnClose) {
      restoreOnClose = false;
      queueMicrotask(restoreInvokerFocus);
    }
  }

  function itemFromEvent(event) {
    const content = contentElement();
    return eventPath(event).find(
      (element) =>
        element?.nodeType === 1 &&
        itemRole(element) &&
        element.closest?.('[role="menu"]') === content,
    );
  }

  function handleClick(event) {
    const item = itemFromEvent(event);
    if (!item) {
      onclickcapture?.(event);
      return;
    }

    if (itemIsDisabled(item)) {
      event.preventDefault();
      event.stopImmediatePropagation();
      return;
    }

    closeMenu({ restoreFocus: true });
    onclickcapture?.(event);
  }

  function handleKeydown(event) {
    const items = enabledItems();
    const currentIndex = items.indexOf(focusedElement());
    let nextIndex;

    if (event.key === "Escape") {
      event.preventDefault();
      event.stopPropagation();
      closeMenu({ restoreFocus: true });
    } else if (event.key === "Tab") {
      clearTypeahead();
      closeMenu();
    } else if (event.key === "ArrowDown") {
      nextIndex = currentIndex < 0 ? 0 : (currentIndex + 1) % items.length;
    } else if (event.key === "ArrowUp") {
      nextIndex =
        currentIndex < 0
          ? items.length - 1
          : (currentIndex - 1 + items.length) % items.length;
    } else if (event.key === "Home") {
      nextIndex = 0;
    } else if (event.key === "End") {
      nextIndex = items.length - 1;
    } else if (!handleTypeahead(event)) {
      onkeydown?.(event);
      return;
    }

    if (nextIndex !== undefined && items.length) {
      event.preventDefault();
      focusItem(items[nextIndex]);
    }
    onkeydown?.(event);
  }

  $effect(() => {
    const nextOpen = isOpen;
    queueMicrotask(() => {
      syncInvokerSemantics();

      if (nextOpen) {
        focusEdge(pendingFocus);
        pendingFocus = "first";
        return;
      }

      clearTypeahead();
      menuItems();
      if (restoreOnClose) restoreInvokerFocus();
      restoreOnClose = false;
    });
  });

  onMount(() => {
    const content = contentElement();
    const root = content?.getRootNode?.() ?? document;

    function rememberInvoker(event) {
      const invoker = matchingInvoker(event);
      if (invoker) activeInvoker = invoker;
    }

    function handleInvokerKeydown(event) {
      const invoker = matchingInvoker(event);
      if (!invoker || invoker.matches(":disabled")) return;
      activeInvoker = invoker;

      if (event.key === "ArrowDown" || event.key === "ArrowUp") {
        event.preventDefault();
        openMenu(event.key === "ArrowUp" ? "last" : "first");
      }
    }

    root.addEventListener("keydown", handleInvokerKeydown);
    root.addEventListener("click", rememberInvoker, true);
    syncInvokerSemantics();
    menuItems();

    const observer =
      typeof MutationObserver !== "undefined" && content
        ? new MutationObserver(menuItems)
        : undefined;
    observer?.observe(content, { childList: true, subtree: true });

    return () => {
      observer?.disconnect();
      root.removeEventListener("keydown", handleInvokerKeydown);
      root.removeEventListener("click", rememberInvoker, true);
      clearTypeahead();
    };
  });
</script>

<Popover
  {...contentProps}
  bind:this={popoverElement}
  {id}
  open={isOpen}
  onOpenChange={requestOpen}
  {placement}
  {offset}
  role="menu"
  tabindex={-1}
  data-slot="menu"
  class={twMerge("min-w-40 p-1", className)}
  onclickcapture={handleClick}
  onkeydown={handleKeydown}
>
  {@render children?.({ open: isOpen, close: closeMenu })}
</Popover>
