// docs/.vitepress/theme/components/klean/command/CommandShortcut.vue
<script setup>
import { computed, useAttrs } from 'vue'
import { twMerge } from 'tailwind-merge'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()
const classes = computed(() =>
  twMerge(
    'ml-auto text-xs tracking-widest text-gray-500 dark:text-gray-400',
    attrs.class
  )
)
</script>

<template>
  <kbd
    v-bind="attrs"
    aria-hidden="true"
    data-slot="command-shortcut"
    :class="classes"
  >
    <slot />
  </kbd>
</template>

// docs/klean-ui/sources/command/CommandShortcut.svelte
<script>
  import { twMerge } from "tailwind-merge";
  let { class: className = "", children, ...shortcutProps } = $props();
</script>

<kbd
  {...shortcutProps}
  aria-hidden="true"
  data-slot="command-shortcut"
  class={twMerge(
    "ml-auto text-xs tracking-widest text-gray-500 dark:text-gray-400",
    className,
  )}
>
  {@render children?.()}
</kbd>
